version: '3'
services:
  ctf:
    build: .
    image: tsalvia/ctf_pwn
    tty: true
    stdin_open: true
    privileged: true
    volumes:
    - "${SHARE_DIR_PATH}:/mnt"
    - "${LIBC_DB_PATH}:/opt/libc-database/db"