version: '2'

services:
  ctf_pwn:
    build:
      context: .
    image: ctf_pwn
    container_name: ctf_pwn
    tty: true
    stdin_open: true
    privileged: true
    volumes:
    - "/local/folder:/mnt"
